kyma-project/eventing-auth-manager

- .github/workflows/lint.yml
- CODEOWNERS
- add github workflow for linting using golangci-lint
> add lint action

- cmd/main.go
- controllers/eventingauth_controller.go
- controllers/kyma_controller.go
- controllers/suite_test.go
Use default k8s exponential back-off instead of custom retry which is not exponential
#1
> Use exponential back-off instead of fixed retry

- controllers/eventingauth_controller.go
- controllers/eventingauth_controller_test.go
- controllers/kyma_controller_test.go
- controllers/suite_test.go
- internal/ias/ias_config.go
- internal/ias/ias_config_test.go
- internal/skr/client.go
- internal/skr/client_test.go
- scripts/run-integration-test.sh
Improve integration tests and create integration tests run script for Prow job.
- Improve integration tests
- Improve test clean-up
- Get rid of error.Join usage
-  Create integration tests run script used by Prow job
#20
> Improve Int Tests and Create Int Test Run Script for Pipeline

- Dockerfile
Test new image auto bump by merging the this test commit
> Test auto-bump with a commit

- Dockerfile
Tests the Eventing Auth Manager auto-bump
- Dummy change Dockerfile comment change
> Test Eventing Auth Manager Auto-Bump

- sec-scanners-config.yaml
let's used the prod dir for sec scanning
> change the dir to prod

- Dockerfile
> Bumpd the golang image in the Dockerfile

- sec-scanners-config.yaml
Update image in security config to latest
> Update image in security-config

- sec-scanners-config.yaml
- Bump image in sec scanner config
> Bump image in sec scanner config

- Dockerfile
- Bump GOLANG to 1.21.5 in Dockerfile
> Bump GOLANG to 1.21.5 in Dockerfile

- api/v1alpha1/eventingauth_types.go
- api/v1alpha1/groupversion_info.go
- api/v1alpha1/status.go
- api/v1alpha1/status_test.go
- cmd/main.go
- cmd/main_test.go
- controllers/eventingauth_controller.go
- controllers/eventingauth_controller_test.go
- controllers/kyma_controller.go
- controllers/kyma_controller_test.go
- controllers/stubs_test.go
- controllers/suite_test.go
- internal/ias/client.go
- internal/ias/client_test.go
- internal/ias/ias_config.go
- internal/ias/ias_config_test.go
- internal/ias/internal/api/SCI_Application_Directory.yaml
- internal/ias/internal/api/ias.gen.go
- internal/ias/internal/oidc/oidc-client.go
- internal/ias/internal/oidc/oidc-client_test.go
- internal/ias/types.go
- internal/skr/client.go
- internal/skr/client_test.go
Fix lint issues for the following linters:
- goerr113
- gochecknoinits
- gofumpt
- gochecknoglobals
- stylecheck
- funlen
- nestif
It is easier to review this PR [commit by commit](https://github.com/kyma-project/eventing-auth-manager/pull/116/commits).
> Fix lint issues

- .github/dependabot.yml
Looks like the [`schedule.time`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduletime) has a formatting issue: https://github.com/kyma-project/eventing-auth-manager/pull/125/checks
- Put `schedule.time` in quotes.
> Fix schedule of DependaBot

- .github/workflows/integration-test.yml
- Makefile
- config/crd/bases/operator.kyma-project.io_eventingauths.yaml
- hack/provision-k3d.sh
- run the integration test with a real IAS instance on push (after merging a PR)
> chore: introduce IAS integration test

- controllers/eventingauth_controller_test.go
- controllers/kyma_controller.go
- controllers/kyma_controller_test.go
- controllers/suite_test.go
> fix: update ownerrefs on EA-CR to latest kyma api-version

- cmd/main.go
- controllers/kyma_controller.go
- reconcile Kymas only on CREATE
- include only metadata for kymas in the caches
> feat: reconcile Kymas only on CREATE

- .github/workflows/integration-test.yml
- controllers/suite_test.go
- create a slack notification in team channel if integration test fails
> chore: add slack notification on failure for integration test

- Makefile
> chore: bump kubernetes version for test

- .github/workflows/lint.yml
- .github/workflows/stale.yml
- .gitignore
- .golangci.yaml
- Makefile
- cmd/main.go
- controllers/eventingauth_controller.go
- controllers/eventingauth_controller_test.go
- controllers/kyma_controller.go
- controllers/kyma_controller_test.go
- controllers/stubs_test.go
- controllers/suite_test.go
- internal/ias/client.go
- internal/ias/client_test.go
- internal/ias/ias_config_test.go
- internal/ias/internal/oidc/oidc-client_test.go
- internal/skr/client.go
> chore: add stale action

- .github/workflows/slack-failure-message.json
- Makefile
- add missing slack message
- change k8s to 1.28.4
> fix: change k8s version in test

- sec-scanners-config.yaml
- update sec-scanner-config.yaml
> chore: bump sec-scanner-config

- controllers/suite_test.go
- a little safety measure: do not delete system namespaces after a test
> fix: dont delete system namespaces after test

- .github/workflows/create-release.yml
- hack/scripts/await_pr_merge.sh
- hack/scripts/check_artifacts_existence.sh
- hack/scripts/check_publish_release_prerequisites.sh
- hack/scripts/check_release_tag.sh
- hack/scripts/create_draft_release.sh
- hack/scripts/create_scan_config.sh
- hack/scripts/create_sec_scanner_bump_pr.sh
- hack/scripts/publish_release.sh
- hack/scripts/releaselabelvalidator/release_label_validator.py
- hack/scripts/releaselabelvalidator/requirements.txt
- added release pipeline.
- https://github.com/kyma-project/eventing-auth-manager/issues/149
> chore: added release pipeline

- .github/workflows/create-release.yml
- updated unit tests in release pipeline
- added integration tests in release pipeline
- https://github.com/kyma-project/eventing-auth-manager/issues/149
> fix: updated unit and integration tests in release pipeline

- Dockerfile
- go.mod
> chore: update go version to 1.22.2

- controllers/eventingauth_controller.go
- controllers/eventingauth_controller_test.go
- updates CR status when application secret already exists on cluster
- https://github.com/kyma-project/eventing-auth-manager/issues/163
> fix: updates CR status when application secret already exists on cluster

- .github/release.yml
- .github/workflows/create-release.yml
- enabled validate labels step in create release workflow
- https://github.com/kyma-project/eventing-auth-manager/issues/149
> chore: enabled validate labels step in create release workflow

- README.md
- Added mandatory sections to README.md
https://github.com/kyma-project/community/issues/926
> docs: add mandatory sections to readme

- .github/workflows/pull-build-image.yaml
- .github/workflows/push-build-image.yaml
- .github/workflows/tag-build-image.yaml
- added github action based build jobs
> chore: added github action based build jobs

- .github/workflows/create-release.yml
- update token used in release pipeline
> chore: update token used in release pipeline

- go.mod
- go.sum
Upgrade golang-jwt to fix the security issue
**Security Issue**: https://www.mend.io/vulnerability-database/CVE-2024-51744
> fix: upgrade golang-jwt to fix security issue

- hack/scripts/create_scan_config.sh
- sec-scanners-config.yaml
- updated sec-scanners-config format
- https://github.com/kyma-project/kyma-companion/issues/384
> fix: updated sec-scanners-config format
